language: python
python:
    - "3.6"

# Install dependencies
install:
    - pip install -r requirements.txt

# Run tests
script:
     - pytest tests/v1/test_meetups.py

after_success:
    - coveralls
#
# branches:
#     only:
#         - develop
