language: python
python:
    - "3.6"

# Install dependencies
install:
    - pip install -r requirements.txt

# Run tests
script:
     - pytest --cov=app

after_success:
    - coveralls
#
# branches:
#     only:
#         - develop
